name: Deploy to Ubuntu Server
on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거
jobs: #진행되는 잡에 대한 정보
  build: # 진행되는 순서 - 빌드를 진행함
    runs-on: ubuntu-latest #어느환경에서 실행할래? 개발 서버를 말함
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Setup Java JDK
      uses: actions/setup-java@v4.4.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Set SSH key permissions #개인키 만드는 부분
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa    # 환경설정 변수명 SERVER_SSH_KEY <-- 이건 자유
        chmod 600 ~/.ssh/id_rsa
    - name: Add SSH key  #액션을 이용하여 개인키 만드는 부분
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}  #해당 깃허브 리파지토리 셋팅에서 secrets에 개발서버 개인키 등록
    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 43.201.110.51 >> ~/.ssh/known_hosts  # known_hosts에 서버 아이피에 관한것을 등록해주는 작업
        #              알고리즘  운영서버 주소
    - name: Deploy to Server
      run: scp build/libs/*.jar ubuntu@43.201.110.51:~/
